media:
  input: public/assets
  output: /assets
  categories: ["image"]

content:
  - name: entries
    label: Entries
    type: collection
    path: content/entries
    view:
      fields: [image, title, year]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: year, label: Year, type: string }
      - { name: premiereCity, label: Premiere City, type: string }
      - { name: tagline, label: Tagline, type: string }
      - { name: image, label: Main Image, type: image }
      - name: gallery
        label: Image Gallery
        type: image
        list: true
      - { name: artistStatement, label: Artist Statement, type: rich-text }
      - { name: exhibitions, label: Exhibitions, type: rich-text }
      - { name: acknowledgements, label: Acknowledgements, type: rich-text }

  - name: artworks
    label: Artworks
    type: collection
    path: content/artworks
    view:
      fields: [image, title, year]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: year, label: Year, type: string }
      - { name: premiereCity, label: Premiere City, type: string }
      - { name: tagline, label: Tagline, type: string }
      - { name: artistStatement, label: Artist Statement, type: rich-text }
      - { name: exhibitions, label: Exhibitions, type: rich-text }
      - { name: acknowledgements, label: Acknowledgements, type: rich-text }
      - { name: image, label: Main Image, type: image }
      - name: gallery
        label: Image Gallery
        type: image
        list: true

  - name: news
    label: News
    type: collection
    path: content/news
    view:
      fields: [image, title, year]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: year, label: Year, type: string }
      - { name: location, label: Location, type: string }
      - { name: city, label: City, type: string }
      - { name: eventType, label: Event Type, type: string }
      - { name: statement, label: Statement, type: rich-text }
      - { name: image, label: Main Image, type: image }
      - name: gallery
        label: Image Gallery
        type: image
        list: true

  - name: about
    label: About
    type: file
    path: content/about.md
    fields:
      - { name: bio, label: Bio, type: rich-text }
      - { name: exhibitionsAppearances, label: Exhibitions & Appearances, type: rich-text }
      - { name: awardsCommissions, label: Awards & Commissions, type: rich-text }
      - { name: pressMentions, label: Press & Mentions, type: rich-text }
      - { name: image, label: Profile Image, type: image }