media:
  input: public/assets
  output: /assets
  categories: ["image"]

content:
  - name: about
    label: About
    type: file
    path: content/about.md
    fields:
      - { name: bio, label: Bio, type: rich-text }
      - { name: exhibitionsAppearances, label: Exhibitions & Appearances, type: rich-text }
      - { name: awardsCommissions, label: Awards & Commissions, type: rich-text }
      - { name: pressMentions, label: Press & Mentions, type: rich-text }
      - { name: image, label: Profile Image, type: image }

  - name: artworks
    label: Artworks
    type: collection
    path: content/artworks
    view:
      fields: [image, title, year, tagline, premiereCity, featureOrder]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: year, label: Year, type: number }
      - { name: tagline, label: Tagline, type: string }
      - { name: showMedium, label: Show Medium?, type: boolean, default: false }
      - { name: medium, label: Medium, type: string }
      - { name: featured, label: Featured on Front Page?, type: boolean }
      - { name: featureOrder, label: Feature Order, type: number }
      - { name: premiereCity, label: Premiere City, type: string }
      - { name: exhibitions, label: Exhibitions, type: rich-text }
      - { name: artistStatement, label: Artist Statement, type: rich-text }
      - { name: acknowledgements, label: Acknowledgements, type: rich-text }
      - { name: image, label: Main Image, type: image }
      - name: gallery
        label: Image Gallery
        type: image
        list: true

  - name: news
    label: News
    type: collection
    path: content/news
    view:
      fields: [image, title, location, city, date, endDate, eventType]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: subheading, label: Subheading, type: string }
      - { name: isDateRange, label: Date Range?, type: boolean, default: false }
      - { name: date, label: Date / Start Date, type: date }
      - { name: endDate, label: End Date, type: date }
      - { name: location, label: Location, type: string }
      - { name: city, label: City, type: string }
      - name: eventType
        label: Event Type
        type: select
        options:
          values: [Award, Screening, Solo exhibition, Group exhibition, Artist Talk, Press]
      - { name: statement, label: Statement, type: rich-text }
      - { name: image, label: Main Image, type: image }
      - name: gallery
        label: Image Gallery
        type: image
        list: true